services:
  postgres:
    image: postgres:latest
    container_name: db_movie_here
    environment:
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: movie_here 
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    restart: always 

  redis:
    image: redis:latest
    container_name: redis_movie_here
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres-data:
    driver: local